// ---------------------------------------------------------------------------
// BotDiff Champion Knowledge (compact, deterministic)
//
// A small, curated knowledge base used by the Build & Matchup coach. It is NOT
// generated by AI and never invents champion facts — it encodes well-known
// threat tags and ADC build archetypes so recommendations are grounded in the
// real match's champions. Unknown champions simply contribute nothing.
//
// PURE + client-safe.
// ---------------------------------------------------------------------------

export type ThreatTag =
  | "ap"
  | "ad"
  | "cc"
  | "dive"
  | "assassin"
  | "poke"
  | "tank"
  | "engage";

/** Threat tags for common champions (partial by design). */
export const CHAMPION_TAGS: Record<string, ThreatTag[]> = {
  // Assassins / divers
  Zed: ["ad", "assassin", "dive"],
  Talon: ["ad", "assassin", "dive"],
  Katarina: ["ap", "assassin", "dive"],
  Akali: ["ap", "assassin", "dive"],
  Fizz: ["ap", "assassin", "dive"],
  Kassadin: ["ap", "assassin", "dive"],
  "Kha'Zix": ["ad", "assassin", "dive"],
  Rengar: ["ad", "assassin", "dive"],
  Nocturne: ["ad", "assassin", "dive"],
  Diana: ["ap", "assassin", "dive", "engage"],
  Evelynn: ["ap", "assassin", "dive"],
  Yasuo: ["ad", "dive"],
  Yone: ["ad", "dive"],
  Irelia: ["ad", "dive", "cc"],
  Camille: ["ad", "dive", "cc"],
  // Engage / CC tanks & bruisers
  Malphite: ["ap", "tank", "engage", "cc"],
  Leona: ["tank", "engage", "cc"],
  Nautilus: ["tank", "engage", "cc"],
  Rell: ["tank", "engage", "cc"],
  Alistar: ["tank", "engage", "cc"],
  Thresh: ["cc", "engage"],
  Blitzcrank: ["cc", "engage"],
  Pyke: ["ad", "assassin", "cc"],
  Amumu: ["ap", "tank", "engage", "cc"],
  Sejuani: ["tank", "engage", "cc"],
  Zac: ["ap", "tank", "engage", "cc"],
  Ornn: ["ap", "tank", "cc"],
  Sion: ["tank", "engage", "cc"],
  Maokai: ["ap", "tank", "cc", "engage"],
  Rammus: ["tank", "engage"],
  JarvanIV: ["ad", "tank", "engage", "cc"],
  Vi: ["ad", "dive", "cc"],
  Wukong: ["ad", "engage", "cc"],
  // Poke / control mages
  Xerath: ["ap", "poke", "cc"],
  Ziggs: ["ap", "poke"],
  Zoe: ["ap", "poke", "cc"],
  Lux: ["ap", "poke", "cc"],
  "Vel'Koz": ["ap", "poke", "cc"],
  Jayce: ["ad", "poke"],
  Nidalee: ["ap", "poke"],
  Varus: ["ad", "poke"],
  Ezreal: ["ad", "poke"],
  Caitlyn: ["ad", "poke"],
  Karma: ["ap", "poke", "cc"],
  Morgana: ["ap", "cc"],
  Zyra: ["ap", "poke", "cc"],
  Brand: ["ap", "poke", "cc"],
  Syndra: ["ap", "poke", "cc"],
  Orianna: ["ap", "cc", "engage"],
  Viktor: ["ap", "poke"],
  Ahri: ["ap", "assassin", "cc"],
  // Enchanters / utility
  Lulu: ["ap", "cc"],
  Janna: ["ap", "cc"],
  Nami: ["ap", "cc"],
  Soraka: ["ap"],
  Yuumi: ["ap"],
  Milio: ["ap"],
  Renata: ["ap", "cc"],
  // Bruisers / tanks top
  Darius: ["ad", "cc"],
  Garen: ["ad"],
  Sett: ["ad", "cc", "engage"],
  Mordekaiser: ["ap", "dive"],
  Fiora: ["ad", "dive"],
  Jax: ["ad", "dive", "cc"],
  ChoGath: ["ap", "tank", "cc"],
  // Marksmen (as enemies)
  Draven: ["ad"],
  Jinx: ["ad"],
  "Kai'Sa": ["ad", "dive"],
  Vayne: ["ad", "dive"],
  Samira: ["ad", "dive", "engage"],
  Tristana: ["ad", "dive"],
  Lucian: ["ad"],
  Ashe: ["ad", "cc"],
  Jhin: ["ad", "cc"],
  MissFortune: ["ad"],
  Sivir: ["ad"],
  Xayah: ["ad", "cc"],
  Aphelios: ["ad"],
  Zeri: ["ad"],
  "Kog'Maw": ["ad"],
  Twitch: ["ad"],
};

export function tagsFor(champion: string): ThreatTag[] {
  return CHAMPION_TAGS[champion] ?? [];
}

export interface ThreatProfile {
  known: number;
  total: number;
  ap: number;
  ad: number;
  cc: number;
  dive: number; // assassins + divers
  poke: number;
  tank: number;
  engage: number;
}

export function threatProfile(champions: string[]): ThreatProfile {
  const p: ThreatProfile = { known: 0, total: champions.length, ap: 0, ad: 0, cc: 0, dive: 0, poke: 0, tank: 0, engage: 0 };
  for (const c of champions) {
    const tags = tagsFor(c);
    if (tags.length === 0) continue;
    p.known++;
    if (tags.includes("ap")) p.ap++;
    if (tags.includes("ad")) p.ad++;
    if (tags.includes("cc")) p.cc++;
    if (tags.includes("dive") || tags.includes("assassin")) p.dive++;
    if (tags.includes("poke")) p.poke++;
    if (tags.includes("tank")) p.tank++;
    if (tags.includes("engage")) p.engage++;
  }
  return p;
}

// --- ADC build archetypes --------------------------------------------------

export type AdcArchetype = "crit" | "onhit" | "lethality" | "utility" | "hybrid";

export interface AdcBuild {
  archetype: AdcArchetype;
  keystone: string;
  startItem: string;
  core: string[]; // core build order
  playstyle: string; // one line identity
  primaryTree: string;
  secondaryTree: string;
}

const GENERIC_CRIT: AdcBuild = {
  archetype: "crit",
  keystone: "Lethal Tempo",
  startItem: "Doran's Blade + Health Potion",
  core: ["Kraken Slayer / Infinity Edge", "Berserker's Greaves", "Infinity Edge", "Lord Dominik's Regards"],
  playstyle: "Scaling crit carry — reach two items, then win extended fights with sustained auto damage.",
  primaryTree: "Precision",
  secondaryTree: "Domination (Precision secondary vs sustain)",
};

export const ADC_BUILDS: Record<string, AdcBuild> = {
  Jinx: { archetype: "crit", keystone: "Lethal Tempo", startItem: "Doran's Blade", core: ["Kraken Slayer", "Berserker's Greaves", "Runaan's Hurricane", "Infinity Edge"], playstyle: "Reset-hungry hypercarry — snowball resets and shred in extended fights.", primaryTree: "Precision", secondaryTree: "Inspiration" },
  Caitlyn: { archetype: "crit", keystone: "Fleet Footwork", startItem: "Doran's Blade", core: ["The Collector / Kraken Slayer", "Berserker's Greaves", "Infinity Edge", "Rapid Firecannon"], playstyle: "Lane bully — abuse range and trap zoning, snowball the lead into towers.", primaryTree: "Precision", secondaryTree: "Inspiration" },
  Ashe: { archetype: "utility", keystone: "Lethal Tempo", startItem: "Doran's Blade", core: ["Kraken Slayer", "Berserker's Greaves", "Runaan's Hurricane", "Infinity Edge"], playstyle: "Utility marksman — perma-slow, ult engage/peel, safe scaling.", primaryTree: "Precision", secondaryTree: "Sorcery" },
  MissFortune: { archetype: "lethality", keystone: "Press the Attack", startItem: "Doran's Blade", core: ["The Collector", "Berserker's Greaves", "Infinity Edge", "Lord Dominik's Regards"], playstyle: "Lane pressure + teamfight ult — burst carries then unload ultimate in fights.", primaryTree: "Precision", secondaryTree: "Domination" },
  Sivir: { archetype: "crit", keystone: "Lethal Tempo", startItem: "Doran's Blade", core: ["Kraken Slayer / Essence Reaver", "Berserker's Greaves", "Infinity Edge", "Runaan's Hurricane"], playstyle: "Waveclear + engage tool — spellshield picks, ult to start fights.", primaryTree: "Precision", secondaryTree: "Sorcery" },
  Ezreal: { archetype: "lethality", keystone: "First Strike", startItem: "Doran's Blade / Tear", core: ["Trinity Force", "Sorcerer's Shoes / Berserker's", "Serylda's Grudge", "Muramana (from Tear)"], playstyle: "Poke + skirmish — safe Q poke, kite with E, scale on Manamune.", primaryTree: "Inspiration", secondaryTree: "Precision" },
  "Kai'Sa": { archetype: "hybrid", keystone: "Hail of Blades", startItem: "Doran's Blade", core: ["Kraken Slayer / Nashor's Tooth", "Berserker's Greaves", "Infinity Edge / Rabadon's", "Guinsoo's Rageblade"], playstyle: "Flex carry — build to your evolves and dive backline once ahead.", primaryTree: "Domination", secondaryTree: "Precision" },
  Vayne: { archetype: "onhit", keystone: "Lethal Tempo", startItem: "Doran's Blade", core: ["Blade of the Ruined King", "Berserker's Greaves", "Kraken Slayer", "Guinsoo's Rageblade"], playstyle: "Late-game duelist — kite with Q/condemn, melt tanks with % true damage.", primaryTree: "Precision", secondaryTree: "Domination" },
  Twitch: { archetype: "onhit", keystone: "Lethal Tempo", startItem: "Doran's Blade", core: ["Blade of the Ruined King / Kraken Slayer", "Berserker's Greaves", "Runaan's Hurricane", "Infinity Edge"], playstyle: "Ambush carry — flank from stealth and spread damage with ult.", primaryTree: "Precision", secondaryTree: "Domination" },
  Jhin: { archetype: "lethality", keystone: "Fleet Footwork", startItem: "Doran's Blade", core: ["The Collector", "Berserker's Greaves", "Rapid Firecannon", "Infinity Edge"], playstyle: "Burst + zone control — 4th-shot execute, root traps, teamfight from range.", primaryTree: "Precision", secondaryTree: "Sorcery" },
  Lucian: { archetype: "crit", keystone: "Press the Attack", startItem: "Doran's Blade", core: ["Essence Reaver / The Collector", "Berserker's Greaves", "Infinity Edge", "Navori Quickblades"], playstyle: "Early-game lane dominator — trade with double-shot, snowball before falloff.", primaryTree: "Precision", secondaryTree: "Domination" },
  Draven: { archetype: "crit", keystone: "Lethal Tempo", startItem: "Doran's Blade", core: ["The Collector", "Berserker's Greaves", "Infinity Edge", "Bloodthirster"], playstyle: "Snowball lane — keep axes up, convert Adoration gold into a lead.", primaryTree: "Precision", secondaryTree: "Domination" },
  Tristana: { archetype: "crit", keystone: "Lethal Tempo", startItem: "Doran's Blade", core: ["Kraken Slayer", "Berserker's Greaves", "Infinity Edge", "Rapid Firecannon"], playstyle: "All-in diver — reset jumps in fights, explode a target then leap out.", primaryTree: "Precision", secondaryTree: "Domination" },
  Zeri: { archetype: "onhit", keystone: "Lethal Tempo", startItem: "Doran's Blade", core: ["Statikk Shiv / Kraken", "Berserker's Greaves", "Rapid Firecannon", "Infinity Edge"], playstyle: "Mobile skirmisher — kite with move-speed, whittle down in prolonged fights.", primaryTree: "Precision", secondaryTree: "Resolve" },
  Xayah: { archetype: "crit", keystone: "Lethal Tempo", startItem: "Doran's Blade", core: ["Kraken Slayer", "Berserker's Greaves", "Infinity Edge", "Runaan's Hurricane"], playstyle: "Self-peel carry — bank feathers, ult the enemy engage, then unload.", primaryTree: "Precision", secondaryTree: "Domination" },
  Samira: { archetype: "crit", keystone: "Hail of Blades", startItem: "Doran's Blade", core: ["The Collector", "Berserker's Greaves", "Infinity Edge", "Bloodthirster"], playstyle: "Chaotic dive carry — build the S combo, ult when the fight collapses.", primaryTree: "Precision", secondaryTree: "Domination" },
  Aphelios: { archetype: "crit", keystone: "Press the Attack", startItem: "Doran's Blade", core: ["Infinity Edge", "Berserker's Greaves", "Runaan's Hurricane", "Lord Dominik's Regards"], playstyle: "Weapon-cycle carry — plan combos around your gun rotation, scale hard.", primaryTree: "Precision", secondaryTree: "Sorcery" },
  "Kog'Maw": { archetype: "onhit", keystone: "Lethal Tempo", startItem: "Doran's Blade", core: ["Blade of the Ruined King", "Berserker's Greaves", "Guinsoo's Rageblade", "Runaan's Hurricane"], playstyle: "Hyper-scaler — needs peel, then melts everything from max range.", primaryTree: "Precision", secondaryTree: "Resolve" },
  Nilah: { archetype: "onhit", keystone: "Conqueror", startItem: "Doran's Blade", core: ["Blade of the Ruined King", "Berserker's Greaves", "Kraken Slayer", "Guinsoo's Rageblade"], playstyle: "Melee duelist — all-in with shroud + ult, sustain through extended fights.", primaryTree: "Precision", secondaryTree: "Resolve" },
  Varus: { archetype: "lethality", keystone: "Press the Attack", startItem: "Doran's Blade", core: ["The Collector / Manamune", "Berserker's Greaves", "Infinity Edge", "Lord Dominik's Regards"], playstyle: "Poke + pick — chunk with Q, chain-CC with ult for engages.", primaryTree: "Precision", secondaryTree: "Sorcery" },
  Smolder: { archetype: "crit", keystone: "Fleet Footwork", startItem: "Doran's Blade", core: ["Guinsoo's Rageblade / IE", "Berserker's Greaves", "Infinity Edge", "Rapid Firecannon"], playstyle: "Stack-to-scale — farm Q stacks safely, become a ranged execute late.", primaryTree: "Precision", secondaryTree: "Sorcery" },
};

export function buildFor(champion: string): AdcBuild {
  return ADC_BUILDS[champion] ?? GENERIC_CRIT;
}

// --- damage profile + itemization validation -------------------------------
// Used by Item Review so BotDiff NEVER recommends impossible items (e.g. AD
// items for an AP champion). These now delegate to the League Knowledge module
// (the single source of truth for champion metadata) instead of re-deriving
// facts here. When the champion's damage profile can't be confidently
// identified, callers should say nothing rather than guess.
import {
  championDamageProfile,
  hasChampionIdentity,
  isHealSource,
  type DamageProfile,
} from "./league-knowledge";

export type { DamageProfile } from "./league-knowledge";

export function damageProfileFor(champion: string): DamageProfile {
  return championDamageProfile(champion);
}

/** Do we confidently know this champion well enough to coach itemization? */
export function canCoachItemization(champion: string): boolean {
  return hasChampionIdentity(champion) && championDamageProfile(champion) !== "unknown";
}

/** Enemy champions with meaningful healing/sustain — cue for grievous wounds. */
export function healThreatCount(champions: string[]): number {
  return champions.filter((c) => isHealSource(c)).length;
}
