// ---------------------------------------------------------------------------
// BotDiff Structured Player Memory
//
// A real coach carries a memory between sessions. This is that memory as a
// STRUCTURED object — never generated by AI. Future OpenAI requests receive
// this verbatim so the coach can naturally reference past coaching
// ("Last week we focused on recall timing — you're improving") without ever
// inventing anything.
//
// PURE + client-safe. Derived deterministically from the CoachDossier.
// ---------------------------------------------------------------------------
import type { CoachDossier } from "../player-memory";
import type { MatchAnalysisInput } from "../coaching-engine";
import { buildBehaviorObservations } from "./behavior-engine";
import type { Pillar } from "./pillars";
import { categoryToPillar } from "./pillars";

export interface PlayerMemory {
  primaryRole: string;
  championPool: string[];
  preferredChampions: string[];
  currentCoachingFocus: string;
  currentFocusPillar: Pillar;
  biggestStrength: string;
  biggestWeakness: string;
  recurringHabits: string[];
  recentImprovements: string[];
  currentTrend: "improving" | "declining" | "steady";
  recentCoachingTopics: string[];
  lastCoachingUpdate: string; // ISO timestamp
}

export function buildPlayerMemory(
  d: CoachDossier,
  inputs?: MatchAnalysisInput[],
): PlayerMemory {
  const role = inputs?.[0]?.role ?? "Bot / ADC";
  const pool = d.championAdvice.map((c) => c.name);
  const preferred = [...d.championAdvice]
    .sort((a, b) => b.winRate - a.winRate || b.games - a.games)
    .slice(0, 2)
    .map((c) => c.name);

  const topWeakness = d.weaknessPatterns[0];
  const focusPillar: Pillar = topWeakness
    ? categoryToPillar(topWeakness.category)
    : "consistency";

  const improvements = d.trends
    .filter((t) => t.improved && t.direction !== "flat")
    .map((t) => `${t.label} (${t.previous} → ${t.current})`);

  const declines = d.trends.filter((t) => !t.improved && t.direction !== "flat");
  const trend: PlayerMemory["currentTrend"] =
    d.consistency.weeklyTrend > 3 || improvements.length > declines.length + 1
      ? "improving"
      : d.consistency.weeklyTrend < -3 || declines.length > improvements.length + 1
        ? "declining"
        : "steady";

  const topics = buildBehaviorObservations(d)
    .slice(0, 4)
    .map((o) => o.label);

  return {
    primaryRole: role,
    championPool: pool,
    preferredChampions: preferred.length ? preferred : pool.slice(0, 2),
    currentCoachingFocus: d.improvementPlan.biggestWeakness,
    currentFocusPillar: focusPillar,
    biggestStrength: d.primaryStrength.title,
    biggestWeakness: d.primaryWeakness.title,
    recurringHabits: d.recurringHabits.map((h) => h.title),
    recentImprovements: improvements,
    currentTrend: trend,
    recentCoachingTopics: topics,
    lastCoachingUpdate: new Date().toISOString(),
  };
}