// ---------------------------------------------------------------------------
// BotDiff Structured Player Memory
//
// A real coach carries a memory between sessions. This is that memory as a
// STRUCTURED object — never generated by AI. Future OpenAI requests receive
// this verbatim so the coach can naturally reference past coaching
// ("Last week we focused on recall timing — you're improving") without ever
// inventing anything.
//
// PURE + client-safe. Derived deterministically from the CoachDossier.
// ---------------------------------------------------------------------------
import type { CoachDossier } from "../player-memory";
import type { MatchAnalysisInput } from "../coaching-engine";
import { buildBehaviorObservations } from "./behavior-engine";
import type { Pillar } from "./pillars";
import { categoryToPillar } from "./pillars";
import { detectHabits, type DetectedHabit } from "./habit-engine";
import { dominantRole, ROLE_LABELS, type RoleId } from "./role-intelligence";

export interface PlayerMemory {
  primaryRole: string;
  championPool: string[];
  preferredChampions: string[];
  currentCoachingFocus: string;
  currentFocusPillar: Pillar;
  biggestStrength: string;
  biggestWeakness: string;
  recurringHabits: string[];
  recentImprovements: string[];
  currentTrend: "improving" | "declining" | "steady";
  recentCoachingTopics: string[];
  lastCoachingUpdate: string; // ISO timestamp
}

export function buildPlayerMemory(
  d: CoachDossier,
  inputs?: MatchAnalysisInput[],
): PlayerMemory {
  const role = inputs?.[0]?.role ?? "Bot / ADC";
  const pool = d.championAdvice.map((c) => c.name);
  const preferred = [...d.championAdvice]
    .sort((a, b) => b.winRate - a.winRate || b.games - a.games)
    .slice(0, 2)
    .map((c) => c.name);

  const topWeakness = d.weaknessPatterns[0];
  const focusPillar: Pillar = topWeakness
    ? categoryToPillar(topWeakness.category)
    : "consistency";

  const improvements = d.trends
    .filter((t) => t.improved && t.direction !== "flat")
    .map((t) => `${t.label} (${t.previous} → ${t.current})`);

  const declines = d.trends.filter((t) => !t.improved && t.direction !== "flat");
  const trend: PlayerMemory["currentTrend"] =
    d.consistency.weeklyTrend > 3 || improvements.length > declines.length + 1
      ? "improving"
      : d.consistency.weeklyTrend < -3 || declines.length > improvements.length + 1
        ? "declining"
        : "steady";

  const topics = buildBehaviorObservations(d)
    .slice(0, 4)
    .map((o) => o.label);

  return {
    primaryRole: role,
    championPool: pool,
    preferredChampions: preferred.length ? preferred : pool.slice(0, 2),
    currentCoachingFocus: d.improvementPlan.biggestWeakness,
    currentFocusPillar: focusPillar,
    biggestStrength: d.primaryStrength.title,
    biggestWeakness: d.primaryWeakness.title,
    recurringHabits: d.recurringHabits.map((h) => h.title),
    recentImprovements: improvements,
    currentTrend: trend,
    recentCoachingTopics: topics,
    lastCoachingUpdate: new Date().toISOString(),
  };
}

// ---------------------------------------------------------------------------
// Layered Player Memory (Sprint: Coach IQ)
//
// A real coach remembers a player on three levels. This splits the flat memory
// into reusable layers so every future role plugs into the same structure:
//
//   Universal Memory — role-independent: decision-making, objectives,
//                      consistency, mental tendencies, improvement history.
//   Role Memory      — habits specific to the role they play (ADC today).
//   Champion Memory  — per-champion habits, improvements, matchup + mastery.
//
// PURE + client-safe. Derived deterministically from the dossier + inputs.
// ---------------------------------------------------------------------------
export interface UniversalMemory {
  decisionMaking: string;
  objectiveControl: string;
  consistency: string;
  mentalTendencies: string;
  improvementHistory: string;
}

export interface RoleMemory {
  role: RoleId;
  roleLabel: string;
  habits: { label: string; kind: "strength" | "weakness"; evidence: string }[];
  focus: string;
}

export interface ChampionMemory {
  name: string;
  games: number;
  winRate: number;
  habits: { label: string; kind: "strength" | "weakness"; evidence: string }[];
  improvement: string;
  matchups: string;
  masteryTrend: "rising" | "steady" | "falling";
}

export interface LayeredPlayerMemory {
  universal: UniversalMemory;
  role: RoleMemory;
  champions: ChampionMemory[];
  lastUpdated: string;
}

function habitLine(h: DetectedHabit) {
  return { label: h.label, kind: h.kind, evidence: h.evidence.sentences[0] };
}

export function buildLayeredPlayerMemory(
  d: CoachDossier,
  inputs: MatchAnalysisInput[],
): LayeredPlayerMemory {
  const habits = detectHabits(inputs);
  const role = dominantRole(inputs);

  const universal: UniversalMemory = {
    decisionMaking:
      habits.find((h) => h.pillar === "decision")?.summary ??
      "Your grouping and fight timing are steady — no recurring decision-making leak stands out.",
    objectiveControl:
      habits.find((h) => h.category === "objective")?.summary ??
      "You attend objectives at a reasonable rate; keep setting up earlier for a clearer edge.",
    consistency: d.consistency.explanation,
    mentalTendencies: d.mentalNotes,
    improvementHistory: d.weeklySummary,
  };

  const roleHabits = habits.filter((h) => h.role !== "universal");
  const roleMemory: RoleMemory = {
    role,
    roleLabel: ROLE_LABELS[role],
    habits: (roleHabits.length ? roleHabits : habits).slice(0, 5).map(habitLine),
    focus: d.improvementPlan.biggestWeakness,
  };

  // Champion memory — per-champion habit slices from the same detection engine.
  const byChamp = new Map<string, MatchAnalysisInput[]>();
  for (const m of inputs) {
    const list = byChamp.get(m.champion) ?? [];
    list.push(m);
    byChamp.set(m.champion, list);
  }
  const champions: ChampionMemory[] = [];
  for (const advice of d.championAdvice) {
    const ms = byChamp.get(advice.name) ?? [];
    const champHabits = detectHabits(ms).slice(0, 3).map(habitLine);
    const recent = ms.slice(0, Math.ceil(ms.length / 2));
    const older = ms.slice(Math.ceil(ms.length / 2));
    const recentWr = recent.length ? recent.filter((m) => m.win).length / recent.length : 0;
    const olderWr = older.length ? older.filter((m) => m.win).length / older.length : recentWr;
    const masteryTrend: ChampionMemory["masteryTrend"] =
      recentWr - olderWr > 0.1 ? "rising" : olderWr - recentWr > 0.1 ? "falling" : "steady";
    const opponents = Array.from(
      new Set(ms.map((m) => m.laneOpponent).filter((x): x is string => Boolean(x))),
    );
    champions.push({
      name: advice.name,
      games: advice.games,
      winRate: advice.winRate,
      habits: champHabits,
      improvement: `Your standout on ${advice.name} is "${advice.strength.toLowerCase()}"; the leak to watch is "${advice.weakness.toLowerCase()}".`,
      matchups: opponents.length
        ? `Recent matchups: ${opponents.slice(0, 4).join(", ")}.`
        : "Not enough matchup data yet to profile lane opponents.",
      masteryTrend,
    });
  }

  return {
    universal,
    role: roleMemory,
    champions,
    lastUpdated: new Date().toISOString(),
  };
}