// ---------------------------------------------------------------------------
// Rune Intelligence V1 — namespaced facade object (Sprint 4.7).
//
// The single entry point future coaching engines depend on: Decision Engine,
// Replay Coach, Practice Planner, Match Reports, Champion Intelligence,
// Unified Coaching Context and the future AI Coach.
// ---------------------------------------------------------------------------
import {
  get,
  getProfile,
  getOfficial,
  getName,
  getIcon,
  getOfficialText,
  getDescription,
  getTree,
  getSlot,
  isKeystone,
  getTags,
  getPatch,
  getIdentity,
  getScalingProfile,
  getValueMatrix,
  getDecisionReferences,
  getCurriculumReferences,
  getHabitReferences,
  getReplayReferences,
  getPracticeReferences,
  getRecoveryReferences,
  byTree,
  bySlot,
  keystones,
  findByName,
  isAvailable,
  isCoachingPopulated,
  safeFallback,
} from "./engine";
import {
  allRuneProfiles,
  clearRuneProfiles,
  hydrateRuneIntelligence,
  registerRuneProfiles,
  registeredRuneCount,
  registeredRuneIds,
} from "./registry";

export const RuneIntelligenceV1 = {
  get,
  getProfile,
  getOfficial,
  getName,
  getIcon,
  getOfficialText,
  getDescription,
  getTree,
  getSlot,
  isKeystone,
  getTags,
  getPatch,
  getIdentity,
  getScalingProfile,
  getValueMatrix,
  getDecisionReferences,
  getCurriculumReferences,
  getHabitReferences,
  getReplayReferences,
  getPracticeReferences,
  getRecoveryReferences,
  byTree,
  bySlot,
  keystones,
  findByName,
  isAvailable,
  isCoachingPopulated,
  safeFallback,
  all: allRuneProfiles,
  ids: registeredRuneIds,
  count: registeredRuneCount,
  register: registerRuneProfiles,
  clear: clearRuneProfiles,
  hydrate: hydrateRuneIntelligence,
} as const;

export type RuneIntelligenceV1Facade = typeof RuneIntelligenceV1;
