// ---------------------------------------------------------------------------
// Lane State Intelligence V1 — namespaced facade (Sprint 5.0).
//
// The single entry point consumers depend on: Decision Prioritization Engine,
// Unified Coaching Context, Coaching Pipeline and the future AI Coach.
// ---------------------------------------------------------------------------
import {
  allInThreatFrom,
  buildLaneState,
  defaultLaneContext,
  fundamentalsFor,
  getCurriculumReferences,
  getDecisionPriorities,
  getDecisionReferences,
  getFundamentals,
  getHabitReferences,
  getLanePhase,
  getPracticeReferences,
  getWaveState,
  goldAdvantageFrom,
  healthStateFrom,
  isDegraded,
  isObserved,
  itemSpikeFrom,
  laneControlFrom,
  lanePhaseFromClock,
  lanePriorityFrom,
  laneSafetyFrom,
  laneTempoFrom,
  levelAdvantageFrom,
  minionAdvantageFrom,
  normalizeRole,
  powerSpikeStateFrom,
  recallStateFrom,
  recoveryStateFrom,
  resourceStateFrom,
  safeFallback,
  towerPressureFrom,
  wavePotentialsFrom,
  waveDirectionFrom,
  wavePositionFrom,
} from "./engine";
import { emptyLaneStateProfile, makeLaneStateId } from "./types";

export const LaneStateIntelligenceV1 = {
  build: buildLaneState,
  get: buildLaneState,
  empty: emptyLaneStateProfile,
  id: makeLaneStateId,
  safeFallback,
  isObserved,
  isDegraded,
  normalizeRole,
  defaultLaneContext,
  lanePhaseFromClock,
  // state derivations
  healthStateFrom,
  resourceStateFrom,
  levelAdvantageFrom,
  goldAdvantageFrom,
  minionAdvantageFrom,
  waveDirectionFrom,
  wavePositionFrom,
  wavePotentialsFrom,
  laneTempoFrom,
  lanePriorityFrom,
  laneSafetyFrom,
  laneControlFrom,
  towerPressureFrom,
  recallStateFrom,
  itemSpikeFrom,
  powerSpikeStateFrom,
  recoveryStateFrom,
  allInThreatFrom,
  // reference accessors
  getWaveState,
  getLanePhase,
  getDecisionReferences,
  getDecisionPriorities,
  getCurriculumReferences,
  getHabitReferences,
  getPracticeReferences,
  getFundamentals,
  fundamentalsFor,
} as const;

export type LaneStateIntelligenceV1Facade = typeof LaneStateIntelligenceV1;