// ---------------------------------------------------------------------------
// Seed Role Templates. Curated placeholders — Data Dragon / Riot API will
// enrich these later. Keep facts only; no player evaluation.
// ---------------------------------------------------------------------------
import { emptyRoleTemplate, type RoleTemplate } from "../templates/role";
import type { RoleId } from "../templates/champion";

function seed(id: RoleId, label: string, patch: Partial<RoleTemplate>): RoleTemplate {
  return { ...emptyRoleTemplate(id, label), ...patch };
}

export const TOP_ROLE: RoleTemplate = seed("top", "Top", {
  coreResponsibilities: ["Win / stabilize a solo lane", "Create side-lane pressure", "Flank or front-line in fights"],
  primaryResponsibilities: ["Win / stabilize solo lane", "Use Teleport for map impact"],
  secondaryResponsibilities: ["Create side-lane pressure", "Front-line or flank in fights"],
  teamfightResponsibilities: ["Front-line for carries", "Flank onto backline with TP"],
  resourcePriorities: ["Solo XP", "Wave state", "Teleport timing"],
  objectivePriorities: ["Grubs", "Herald", "Baron"],
  tempoExpectations: ["Freeze when losing", "Slow-push into recall", "Match jungler side"],
  laneResponsibilities: ["Trade in windows", "Manage wave for dive safety"],
  mapResponsibilities: ["Cross-map with Teleport", "Threaten side while team takes objectives"],
  commonHabits: ["Overstaying with low HP", "Wasting Teleport", "Losing wave on recall"],
  commonDecisionCategories: ["wave", "teleport", "trade", "sidelane"],
  successConditions: ["Win side lane", "Convert TP into map advantage", "Front-line fights on cooldown"],
  failureConditions: ["Die pre-6 without trade", "TP down during objective", "Isolated deaths in side"],
  winConditionFramework: ["Convert lane priority into map pressure", "Trade side lane for team objective"],
  primaryWinConditions: ["Win the side lane every wave you're alone", "Save TP for a map-swinging play"],
  secondaryWinConditions: ["Solo-kill lane once ahead", "Push in and free your jungler bot side"],
  lanePriorities: ["Wave control > CS", "Level 2/3/6 spikes", "Freeze when down, crash when up"],
  typicalTempoGoals: ["Match jungler side", "Reset before the enemy top", "Be alive at every side-wave arrival"],
  typicalRecallWindows: ["Before side lane pressure returns", "After crashing a wave into tower", "When TP is up and objective is 60s away"],
  powerSpikePhilosophy: ["Trade tempo for first-item spike", "Delay group timings until side is safe"],
  lateGameResponsibilities: ["Hold a side lane", "TP flank onto backline or Baron", "Absorb pressure to free objectives"],
  teamfightIdentity: "Front-line or flanker — engages or peels based on champion class",
  sideLaneResponsibilities: ["Push waves in when 4 enemies are elsewhere", "Never die 1v1 without vision", "Recall on crash, not on kill"],
  commonMistakes: ["Overstaying with low HP", "Wasting TP on a bad wave", "Losing side lane by grouping too early"],
  commonGoodHabits: ["Crash then recall", "TP saved for objectives", "Ward river before pushing in"],
});

export const JUNGLE_ROLE: RoleTemplate = seed("jungle", "Jungle", {
  coreResponsibilities: ["Path efficiently", "Set up objectives", "Track enemy jungler"],
  primaryResponsibilities: ["Set up neutral objectives", "Track enemy jungler pathing"],
  secondaryResponsibilities: ["Gank winning lanes", "Deep vision on lead"],
  teamfightResponsibilities: ["Peel or engage based on comp", "Frontline pit fights"],
  resourcePriorities: ["Camp respawn timers", "Scuttle crab", "Objective spawns"],
  objectivePriorities: ["Scuttle", "Grubs", "Dragon", "Herald", "Baron"],
  tempoExpectations: ["Full clear vs skirmish path", "Reset before objectives", "Match enemy path"],
  laneResponsibilities: ["Gank winning lanes", "Counter-gank losing lanes"],
  mapResponsibilities: ["Vision around objectives", "Track and mirror enemy jungler"],
  commonHabits: ["Ganking losing lanes without setup", "Ignoring scuttle", "Bad pathing vs enemy"],
  commonDecisionCategories: ["path", "gank", "objective", "vision"],
  successConditions: ["Secure objectives with prio", "Punish enemy jungler pathing"],
  failureConditions: ["Objective taken uncontested", "Repeated failed ganks"],
  winConditionFramework: ["Trade neutrals for tempo", "Fight only with prio + vision"],
  primaryWinConditions: ["Win the objective on your side of the map every spawn", "Path to where you have lane prio"],
  secondaryWinConditions: ["Convert a successful gank into an objective", "Invade with numbers when enemy jungler is tracked away"],
  lanePriorities: ["Gank winning lanes for tempo, not kills", "Counter-gank when lanes are shoved in"],
  typicalTempoGoals: ["Arrive at objectives with a full camp lead", "Be on the objective side 45s before spawn"],
  typicalRecallWindows: ["Before objective spawns", "After a successful gank with full inventory", "When enemy jungler is spotted on the far side"],
  powerSpikePhilosophy: ["Item-2 skirmish spike opens fight windows", "Level 6 unlocks objective attempts"],
  lateGameResponsibilities: ["Baron control", "Vision around pit", "Peel or engage in pit fights"],
  teamfightIdentity: "Objective anchor — smites, peels carries, or engages depending on champion",
  sideLaneResponsibilities: ["Support the side-lane pusher with vision", "Counter-jungle when opposite lane is shoved"],
  commonMistakes: ["Ganking losing lanes with no setup", "Ignoring scuttle prio", "Farming through an objective timer"],
  commonGoodHabits: ["Track enemy jungler start", "Reset before objectives", "Ward pit 60s early"],
});

export const MID_ROLE: RoleTemplate = seed("mid", "Mid", {
  coreResponsibilities: ["Control mid priority", "Roam or match roams", "Set up objectives"],
  primaryResponsibilities: ["Own mid priority", "Match enemy roams"],
  secondaryResponsibilities: ["Roam bot with prio", "Set up objective vision"],
  teamfightResponsibilities: ["Deliver burst on primary target", "Follow up on engage"],
  resourcePriorities: ["Solo XP", "Wave push", "Roam windows"],
  objectivePriorities: ["Prio for scuttle/dragon", "Herald/Baron setup"],
  tempoExpectations: ["Shove before roaming", "Match enemy roam", "Reset with wave crashed"],
  laneResponsibilities: ["Wave prio", "Trade windows", "Punish greedy positioning"],
  mapResponsibilities: ["Roam bot on prio", "Ward river approaches"],
  commonHabits: ["Roaming without prio", "Missing waves", "Failing to match roams"],
  commonDecisionCategories: ["prio", "roam", "wave", "vision"],
  successConditions: ["Win prio into objectives", "Impact side lanes with roams"],
  failureConditions: ["Lose prio + objective", "Die roaming into shove"],
  winConditionFramework: ["Convert prio into map presence", "Force fights with tempo"],
  primaryWinConditions: ["Have mid prio at every objective spawn", "Convert prio into a roam or vision play"],
  secondaryWinConditions: ["Solo-kill mid into a Herald swing", "Roam bot on a shove for a 3v2"],
  lanePriorities: ["Prio over CS when objectives are up", "Trade only on cooldown windows"],
  typicalTempoGoals: ["Crash mid before every objective", "Match the enemy mid's roam every time"],
  typicalRecallWindows: ["Before a planned roam", "After crashing mid into tower", "Just before objective spawns with prio"],
  powerSpikePhilosophy: ["Level 6 opens roam windows", "Item-1 defines skirmish tempo"],
  lateGameResponsibilities: ["Waveclear + prio", "Pick threats around vision", "Follow-up engage with primary damage"],
  teamfightIdentity: "Primary damage or catch tool — bursts priority target or follow-up on engage",
  sideLaneResponsibilities: ["Rarely — only when a mid tower is down and prio is safe"],
  commonMistakes: ["Roaming without prio", "Missing waves for a failed roam", "Failing to match enemy mid's roam"],
  commonGoodHabits: ["Shove before roaming", "Ward river before pushing in", "Match roams turn for turn"],
});

export const ADC_ROLE: RoleTemplate = seed("adc", "ADC", {
  coreResponsibilities: ["Farm safely", "Deal sustained damage", "Position around peel"],
  primaryResponsibilities: ["Scale to item spikes safely", "Deal sustained damage in fights"],
  secondaryResponsibilities: ["Sidelane after 3 items", "Vision around dragon"],
  teamfightResponsibilities: ["Position behind frontline", "Focus reachable target with peel"],
  resourcePriorities: ["CS", "Item spikes", "Sidelane after items"],
  objectivePriorities: ["Dragon", "Baron", "Sidelane after 3-item"],
  tempoExpectations: ["Recall after wave crash", "Group at 2 items", "Sidelane at 3 items"],
  laneResponsibilities: ["Wave management", "Recall timing with support"],
  mapResponsibilities: ["Vision around dragon", "Rotate with tempo"],
  commonHabits: ["Greedy recalls", "Over-farming while team fights", "Poor positioning at objectives"],
  commonDecisionCategories: ["wave", "recall", "positioning", "objective"],
  successConditions: ["Hit item spikes on time", "Deal team-carrying damage"],
  failureConditions: ["Fall behind two items", "Die before dealing damage"],
  winConditionFramework: ["Scale to items", "Fight only with peel + vision"],
  primaryWinConditions: ["Hit item spikes on time and turn them into fights", "Deal sustained damage from a safe position"],
  secondaryWinConditions: ["Sidelane after 3 items to create map pressure", "Trade dragons for lane pressure"],
  lanePriorities: ["CS > trades pre-6", "Push for dragon prio", "Trade only on support engage"],
  typicalTempoGoals: ["Reset around every item component", "Be on dragon side by 45s before spawn"],
  typicalRecallWindows: ["Immediately after crashing a wave", "With enough gold for a component spike", "Before dragon with wave crashed"],
  powerSpikePhilosophy: ["Rush the core item that unlocks your damage curve", "Never fight a phase behind on items"],
  lateGameResponsibilities: ["Deal damage from the safest angle", "Sidelane with vision after 3 items", "Anchor pit fights for the team"],
  teamfightIdentity: "Backline sustained damage — kites, focuses reachable targets, respects engage",
  sideLaneResponsibilities: ["Push side with a vision-setting support", "Recall the moment a fight starts elsewhere"],
  commonMistakes: ["Greedy recall for one more wave", "Farming while team fights an objective", "Standing in engage range without vision"],
  commonGoodHabits: ["Recall on wave crash", "Group for dragon at 2 items", "Vision dragon pit 60s early"],
});

export const SUPPORT_ROLE: RoleTemplate = seed("support", "Support", {
  coreResponsibilities: ["Enable the ADC", "Own vision", "Set up objectives"],
  primaryResponsibilities: ["Own team vision", "Enable the ADC"],
  secondaryResponsibilities: ["Roam on wave push", "Set up objectives 60s early"],
  teamfightResponsibilities: ["Engage or peel on champion identity", "Save carry with utility"],
  resourcePriorities: ["Support quest", "Control wards", "Roam windows"],
  objectivePriorities: ["Dragon vision", "Herald setup", "Baron vision"],
  tempoExpectations: ["Roam on wave push", "Reset with ADC", "Rotate with tempo"],
  laneResponsibilities: ["Trade windows", "Peel or engage", "Ward on wave state"],
  mapResponsibilities: ["Deep vision on lead", "Deny vision on losing side"],
  commonHabits: ["Weak vision score", "Roaming into shove", "Missing engages"],
  commonDecisionCategories: ["vision", "roam", "engage", "peel"],
  successConditions: ["Vision score keeps team informed", "Engages land on primary target"],
  failureConditions: ["No control wards on objective", "Lane 2v1 without engage"],
  winConditionFramework: ["Convert vision into safe objectives", "Enable ADC to scale"],
  primaryWinConditions: ["Own the vision map at every objective", "Enable the ADC's scaling"],
  secondaryWinConditions: ["Roam mid on push for a pick", "Convert a vision denial into a pick"],
  lanePriorities: ["Ward on wave state, not on cooldown", "Set up trades on ADC's cooldowns"],
  typicalTempoGoals: ["Have full vision on the next objective 60s early", "Rotate with the ADC every reset"],
  typicalRecallWindows: ["When Control Ward + component are affordable", "With ADC after crashing a wave", "Before objective vision windows"],
  powerSpikePhilosophy: ["Support quest completion is your item-1", "Prioritize vision items over combat stats"],
  lateGameResponsibilities: ["Live to place wards", "Peel the primary carry", "Sweep enemy vision at pits"],
  teamfightIdentity: "Engage, peel, or catcher — role expressed by champion class",
  sideLaneResponsibilities: ["Rarely — only to escort a sidelane push with vision"],
  commonMistakes: ["Weak vision score", "Roaming into a shoved wave", "Engaging without follow-up"],
  commonGoodHabits: ["Buy Control Wards every reset", "Ward before pushing", "Rotate with ADC as a pair"],
});

export const ROLE_TEMPLATES: Record<RoleId, RoleTemplate> = {
  top: TOP_ROLE,
  jungle: JUNGLE_ROLE,
  mid: MID_ROLE,
  adc: ADC_ROLE,
  support: SUPPORT_ROLE,
};