// ---------------------------------------------------------------------------
// Team Composition Intelligence V1 — namespaced facade (Sprint 4.9).
//
// The single entry point consumers depend on: Decision Prioritization Engine,
// Unified Coaching Context, Coaching Pipeline, Match Reports, Replay Coach,
// Practice Planner and the future AI Coach.
// ---------------------------------------------------------------------------
import {
  analyzeTeam,
  buildRelationships,
  compareCompositions,
  findCompositionsForChampion,
  findCompositionsForRole,
  findRoleForChampion,
  get,
  getAllCompositions,
  getChampionAvailability,
  getChampionContext,
  getComposition,
  getCompositionById,
  getCurriculumReferences,
  getDecisionPriorities,
  getDecisionReferences,
  getHabitReferences,
  getItemReferences,
  getMatchupReferences,
  getObjectiveProfile,
  getPracticeReferences,
  getRuneReferences,
  getScalingProfile,
  getSideLaneProfile,
  getStrengths,
  getTeamfightProfile,
  getTrait,
  getVulnerabilities,
  getWeaknesses,
  getWinConditions,
  isAvailable,
  isKnowledgePopulated,
  safeFallback,
} from "./engine";
import {
  allTeamCompositions,
  clearTeamCompositions,
  registerTeamCompositions,
  registeredCompositionCount,
  registeredCompositionIds,
} from "./registry";
import {
  createTeamCompositionProfile,
  emptyTeamCompositionProfile,
  makeCompositionId,
} from "./types";

export const TeamCompositionIntelligenceV1 = {
  get,
  getComposition,
  getCompositionById,
  getAllCompositions,
  findCompositionsForChampion,
  findCompositionsForRole,
  findRoleForChampion,
  analyzeTeam,
  compareCompositions,
  buildRelationships,
  getWinConditions,
  getStrengths,
  getWeaknesses,
  getVulnerabilities,
  getTrait,
  getTeamfightProfile,
  getScalingProfile,
  getObjectiveProfile,
  getSideLaneProfile,
  getDecisionPriorities,
  getDecisionReferences,
  getCurriculumReferences,
  getHabitReferences,
  getPracticeReferences,
  getItemReferences,
  getRuneReferences,
  getMatchupReferences,
  getChampionAvailability,
  getChampionContext,
  isAvailable,
  isKnowledgePopulated,
  safeFallback,
  create: createTeamCompositionProfile,
  empty: emptyTeamCompositionProfile,
  id: makeCompositionId,
  all: allTeamCompositions,
  ids: registeredCompositionIds,
  count: registeredCompositionCount,
  register: registerTeamCompositions,
  clear: clearTeamCompositions,
} as const;

export type TeamCompositionIntelligenceV1Facade = typeof TeamCompositionIntelligenceV1;
