/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoachingRouteImport } from './routes/coaching'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as ChampionsRouteImport } from './routes/champions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as MatchesIndexRouteImport } from './routes/matches.index'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as ProfileChampionRouteImport } from './routes/profile.$champion'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'
import { Route as CoachingHistoryRouteImport } from './routes/coaching.history'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingRoute = CoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionsRoute = ChampionsRouteImport.update({
  id: '/champions',
  path: '/champions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatchesRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const ProfileChampionRoute = ProfileChampionRouteImport.update({
  id: '/$champion',
  path: '/$champion',
  getParentRoute: () => ProfileRoute,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => MatchesRoute,
} as any)
const CoachingHistoryRoute = CoachingHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CoachingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/champions': typeof ChampionsRoute
  '/coach': typeof CoachRoute
  '/coaching': typeof CoachingRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/matches': typeof MatchesRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/welcome': typeof WelcomeRoute
  '/coaching/history': typeof CoachingHistoryRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/profile/$champion': typeof ProfileChampionRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/matches/': typeof MatchesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/champions': typeof ChampionsRoute
  '/coach': typeof CoachRoute
  '/coaching': typeof CoachingRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/welcome': typeof WelcomeRoute
  '/coaching/history': typeof CoachingHistoryRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/profile/$champion': typeof ProfileChampionRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/matches': typeof MatchesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/champions': typeof ChampionsRoute
  '/coach': typeof CoachRoute
  '/coaching': typeof CoachingRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/matches': typeof MatchesRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/welcome': typeof WelcomeRoute
  '/coaching/history': typeof CoachingHistoryRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/profile/$champion': typeof ProfileChampionRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/matches/': typeof MatchesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/champions'
    | '/coach'
    | '/coaching'
    | '/dashboard'
    | '/matches'
    | '/profile'
    | '/progress'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/welcome'
    | '/coaching/history'
    | '/matches/$matchId'
    | '/profile/$champion'
    | '/settings/profile'
    | '/matches/'
    | '/profile/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/champions'
    | '/coach'
    | '/coaching'
    | '/dashboard'
    | '/progress'
    | '/reset-password'
    | '/sitemap.xml'
    | '/welcome'
    | '/coaching/history'
    | '/matches/$matchId'
    | '/profile/$champion'
    | '/settings/profile'
    | '/matches'
    | '/profile'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/champions'
    | '/coach'
    | '/coaching'
    | '/dashboard'
    | '/matches'
    | '/profile'
    | '/progress'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/welcome'
    | '/coaching/history'
    | '/matches/$matchId'
    | '/profile/$champion'
    | '/settings/profile'
    | '/matches/'
    | '/profile/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChampionsRoute: typeof ChampionsRoute
  CoachRoute: typeof CoachRoute
  CoachingRoute: typeof CoachingRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  MatchesRoute: typeof MatchesRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  ProgressRoute: typeof ProgressRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching': {
      id: '/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof CoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champions': {
      id: '/champions'
      path: '/champions'
      fullPath: '/champions'
      preLoaderRoute: typeof ChampionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/matches/': {
      id: '/matches/'
      path: '/'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/profile/$champion': {
      id: '/profile/$champion'
      path: '/$champion'
      fullPath: '/profile/$champion'
      preLoaderRoute: typeof ProfileChampionRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/coaching/history': {
      id: '/coaching/history'
      path: '/history'
      fullPath: '/coaching/history'
      preLoaderRoute: typeof CoachingHistoryRouteImport
      parentRoute: typeof CoachingRoute
    }
  }
}

interface CoachingRouteChildren {
  CoachingHistoryRoute: typeof CoachingHistoryRoute
}

const CoachingRouteChildren: CoachingRouteChildren = {
  CoachingHistoryRoute: CoachingHistoryRoute,
}

const CoachingRouteWithChildren = CoachingRoute._addFileChildren(
  CoachingRouteChildren,
)

interface MatchesRouteChildren {
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
}

const MatchesRouteChildren: MatchesRouteChildren = {
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  MatchesIndexRoute: MatchesIndexRoute,
}

const MatchesRouteWithChildren =
  MatchesRoute._addFileChildren(MatchesRouteChildren)

interface ProfileRouteChildren {
  ProfileChampionRoute: typeof ProfileChampionRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileChampionRoute: ProfileChampionRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface SettingsRouteChildren {
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChampionsRoute: ChampionsRoute,
  CoachRoute: CoachRoute,
  CoachingRoute: CoachingRouteWithChildren,
  DashboardRoute: DashboardRoute,
  MatchesRoute: MatchesRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  ProgressRoute: ProgressRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
